name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.2
  get: ^4.6.6
  sqflite: ^2.3.3+2
  path: ^1.9.0
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/pokeball.png